# Parameters
nc: 1  # Number of classes (sostituisci con 1 se necessario)
scales:
  # [depth, width, max_channels]
  s: [0.50, 0.50, 1024]  # small

# Backbone
backbone:
  - [-1, 1, Conv,   [64, 3, 2]]                  # 0 - P1/2
  - [-1, 1, Conv,   [128, 3, 2, 1, 2]]           # 1 - P2/4
  - [-1, 2, C3k2,   [256, False, 0.25]]
  - [-1, 1, Conv,   [256, 3, 2, 1, 4]]           # 3 - P3/8
  - [-1, 2, C3k2,   [512, False, 0.25]]
  - [-1, 1, Conv,   [512, 3, 2]]                 # 5 - P4/16
  - [-1, 4, A2C2f,  [512, True, 4]]              # Area Attention ×4
  - [-1, 1, Conv,   [1024, 3, 2]]                # 7 - P5/32
  - [-1, 4, A2C2f,  [1024, True, 1]]             # Deep attention

# Head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]]                    # cat P5 + P4
  - [-1, 2, A2C2f, [512, False, -1]]

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]]                    # cat P4 + P3
  - [-1, 2, A2C2f, [256, False, -1]]

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 11], 1, Concat, [1]]                   # cat head P3 + P4
  - [-1, 2, A2C2f, [512, False, -1]]

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 8], 1, Concat, [1]]                    # cat head P4 + P5
  - [-1, 2, C3k2, [1024, True]]

  - [[14, 17, 20], 1, Detect, [nc]]              # P3, P4, P5


training:
  task: detect
  optimizer: SGD
  lr0: 0.01
  lrf: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 3
  pretrained: False
  cache: False
  save_dir: "/workspace/results"
  project: "/workspace/results"
  epochs: 200
  batch: 64
  save: True
  verbose: True
  save_period: 10
  workers: 2
  device: 0
