# Parameters
nc: 1 # number of classes
scales: 
  # [depth, width, max_channels]
  s: [0.33, 0.50, 1024]

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2  
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4  
  - [-1, 3, C2f, [128, True]]  
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8  
  - [-1, 6, C2f, [256, True]]  
  - [-1, 1, SCDown, [512, 3, 2]] # 5-P4/16  
  - [-1, 6, C2f, [512, True]]  
  - [-1, 1, SCDown, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2fCIB, [1024, True, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 1, PSA, [1024]] # 10

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 11
  - [[-1, 6], 1, Concat, [1]] 
  - [-1, 3, C2f, [512]] # 13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]  # 14
  - [[-1, 4], 1, Concat, [1]] # 15
  - [-1, 3, C2f, [256]] # 16 

  # - [-1, 1, Conv, [256, 3, 2]]
  # - [[-1, 13], 1, Concat, [1]] # cat head P4
  # - [-1, 3, C2f, [512]] # 19 (P4/16-medium)

  # - [-1, 1, SCDown, [512, 3, 2]]
  # - [[-1, 10], 1, Concat, [1]] # cat head P5
  # - [-1, 3, C2fCIB, [1024, True, True]] # 22 (P5/32-large)

  - [[16], 1, v10Detect, [nc]] # Detect(P3, P4, P5)

training:
  task: detect
  optimizer: SGD
  lr0: 0.01
  lrf: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 3
  pretrained: False
  cache: False
  save_dir: "/workspace/results"
  project: "/workspace/results"
  device: 0
  epochs: 200
  batch: 64
  save: True
  verbose: True
  save_period: 10
