# Parameters
nc: 1 # number of classes
scales:
  # [depth, width, max_channels]
  s: [0.50, 0.50, 1024]

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 4, A2C2f, [512, True, 4]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 4, A2C2f, [1024, True, 1]] # 8

head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 2, A2C2f, [512, False, -1]] # 11

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 2, A2C2f, [256, False, -1]] # 14

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 11], 1, Concat, [1]] # cat head P4
  - [-1, 2, A2C2f, [512, False, -1]] # 17

#  - [-1, 1, Conv, [512, 3, 2]]
#  - [[-1, 8], 1, Concat, [1]] # cat head P5
#  - [-1, 2, C3k2, [1024, True]] # 20 (P5/32-large)

  - [[14, 17], 1, Detect, [nc]] # Detect(P3, P4)


training:
  task: detect
  optimizer: SGD
  lr0: 0.01
  lrf: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 3
  pretrained: False
  cache: False
  save_dir: "/workspace/results"
  project: "/workspace/results"
  device: 0
  epochs: 200
  batch: 64
  save: True
  verbose: True
  save_period: 10

#                   from  n    params  module                                       arguments
#  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
#  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
#  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
#  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
#  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
#  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
#  6                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 4]
#  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
#  8                  -1  2   2689536  ultralytics.nn.modules.block.A2C2f           [512, 512, 2, True, 1]
#  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
# 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
# 11                  -1  1    345856  ultralytics.nn.modules.block.A2C2f           [768, 256, 1, False, -1]
# 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
# 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
# 14                  -1  1     95104  ultralytics.nn.modules.block.A2C2f           [512, 128, 1, False, -1]
# 15                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
# 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
# 17                  -1  1    296704  ultralytics.nn.modules.block.A2C2f           [384, 256, 1, False, -1]
# 18            [14, 17]  1    394002  ultralytics.nn.modules.head.Detect           [1, [128, 256]]
#YOLOv12sLightP3P4050 summary: 237 layers, 6,725,970 parameters, 6,725,954 gradients, 19.5 GFLOPs