# Parameters
nc: 1  # number of classes
scales:
  s: [0.33, 0.50, 1024]

# YOLO12n backbone (semplificato: solo P3)
backbone:
  - [-1, 1, Conv, [64, 3, 2]]       # 0 - P1/2
  - [-1, 1, Conv, [128, 3, 2]]      # 1 - P2/4
  - [-1, 2, C3k2, [256, False, 0.25]]  # 2
  - [-1, 1, Conv, [256, 3, 2]]      # 3 - P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]  # 4 - fine backbone

# YOLO12n head (solo P3)
head:
  - [-1, 2, A2C2f, [256, False, -1]]  # 5
  - [[-1], 1, Detect, [nc]]          # 6 - Detect(P3)

training:
  task: detect
  optimizer: SGD
  lr0: 0.01
  lrf: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 3
  pretrained: False
  cache: False
  save_dir: "/workspace/results"
  project: "/workspace/results"
  device: 0
  epochs: 200
  batch: 64
  save: True
  verbose: True
  save_period: 10

#                     from  n    params  module                                       arguments
#  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
#  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
#  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.#25]
#  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
#  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
#  5                  -1  1     78720  ultralytics.nn.modules.block.A2C2f           [256, 128, 1, False, #-1]
#  6                [-1]  1    151249  ultralytics.nn.modules.head.Detect           [1, [128]]
#YOLOv12sUltraLight summary: 56 layers, 526,609 parameters, 526,593 gradients, 8.7 GFLOPs